"""Initial migration - create vault_data table

Revision ID: fca0ebd9cd20
Revises: 
Create Date: 2025-11-16 10:02:03.189931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca0ebd9cd20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vault_address', sa.String(length=42), nullable=False),
    sa.Column('historical_apy', sa.Float(), nullable=True),
    sa.Column('diluted_apy', sa.Float(), nullable=True),
    sa.Column('tvl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_data_vault_address'), 'vault_data', ['vault_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_data_vault_address'), table_name='vault_data')
    op.drop_table('vault_data')
    # ### end Alembic commands ###
